### ISSUE TITLE
Proposition d'arborescence du site Imaginatiiif

### ISSUE THREAD

**Issue by saroulle** [Chartes-TNAH/imago-commentaires#6]
Le site propose un accès au feuilletage et à l'authenfication depuis la page d'accueil.
Les commentaires peuvent être ajoutés depuis la notice de l'oeuvre.
L'accès aux données IIIF se fait à partir d'un lien dans la notice oeuvre.
[imaginatiiif.pdf](https://github.com/Chartes-TNAH/imago-commentaires/files/1781630/imaginatiiif.pdf)

**Comment by saroulle** [comment]
Pour modifier ou compléter l'arborescence : 
https://www.gloomaps.com/tkWjHc6Rao

**Comment by AnZadykhina** [comment]
Je propose d'ajouter browse

**Comment by saroulle** [comment]
Browse correspond à feuilletage en français

**Comment by AnZadykhina** [comment]
J'ai parlé de navigation sur notre site, pas sur les resultats de recherche ou tu parle de la même chose?

**Comment by SybilleClochet** [comment]
J'ai légèrement modifié l'arborescence en renommant l'un des "feuilletage" en Galerie (au même niveau que Recherche et Connexion) et j'ai modifié l'ordre des rubriques principales.

**Comment by TNAHMP** [comment]
J'ai modifié l'arborescence pour qu'elle représente l'état actuel de notre réflexion.
